In [9]:
import pandas as pd

In [10]:
columns = ['person', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11',\
       'c12', 'c13', 'c14', 'c15', 'c16', 'c17', 'c18', 'c19', 'c20', 'c21',\
       'c22', 'c23', 'c24', 'c25', 'c26', 'c27', 'c28', 'c29', 'c30', 'c31',\
       'c32', 'c33', 'c34', 'c35', 'c36', 'c37', 'c38', 'c39', 'c40', 'c41',\
       'c42', 'c43', 'c44', 'c45', 'c46', 'c47', 'c48', 'c49', 'c50', 'c51',\
       'c52', 'c53', 'c54', 'c55', 'c56', 'c57', 'c58', 'O']

In [11]:
print(len(columns))

60

In [12]:
import os
if not os.path.exists('merged files main'):
  os.makedirs('merged files main')

In [14]:
#combine 4 text files into 1 
for j in range(1, 13):
    if j == 8:
        print(j, end = " ")
        main_df = pd.DataFrame(columns = columns)
        for k in range(1,3):
            directory = 'C:\\Users\\Vinay\Gait Analysis\\Filtered Data\\008\\OFF_' + str(k)
            num_files = len(os.listdir(directory))

            for i in range(1,num_files + 1):
                df = pd.read_csv(directory+ '\\task_' + str(i) +'.txt', header = None).iloc[:, 2:]
                df.insert(0, 'person', j)
                df.columns = columns
                main_df = pd.concat([main_df, df], ignore_index = True)
                
        print(main_df.shape)
        main_df.to_csv('C:\\Users\\Vinay\\Gait Analysis\\merged files main\\' + str("{:03d}".format(j) + '.csv'), index = False)
        continue

    else:
        main_df = pd.DataFrame(columns = columns)
        directory = "C:\\Users\\Vinay\Gait Analysis\\Filtered Data\\" + str("{:03d}".format(j))
        num_files = len(os.listdir(directory))
        print(j, end = " ")

        for i in range(1,num_files+1):
            df = pd.read_csv(directory+ '\\task_' + str(i) +'.txt', header = None).iloc[:, 2:]
            df.insert(0, 'person', j)
            df.columns = columns

            main_df = pd.concat([main_df, df], ignore_index = True)
        main_df.to_csv('C:\\Users\\Vinay\\Gait Analysis\\merged files main\\' + str("{:03d}".format(j) + '.csv'), index = False)
        print(main_df.shape)

1 (376504, 60)
2 (268504, 60)
3 (1034504, 60)
4 (322005, 60)
5 (153004, 60)
6 (530504, 60)
7 (343004, 60)
8 (884009, 60)
9 (396006, 60)
10 (803504, 60)
11 (580504, 60)
12 (519004, 60)

In [8]:
a = pd.read_csv('C:\\Users\\Vinay\Gait Analysis\\merged files main\\001.csv')
#a.columns = columns
a

,-,person,time,c1,c2,c3,c4,c5,c6,c7,...,c50,c51,c52,c53,c54,c55,c56,c57,c58,O
0,0,1,12:04:38,7.0640,7.3853,5.3534,6.9240,3.7559,1.7674,4.4223,...,115.000000,53.0,7865.000000,4712.000000,-1087.000000,661.000000,-688.000000,509.000000,1830.000000,0
1,1,1,12:04:38.002,7.8537,7.6998,6.1821,6.9615,3.8015,1.2309,4.1826,...,117.611651,53.0,8055.034673,4661.843221,-1105.551850,657.591356,-723.735803,533.373304,1830.000025,0
2,2,1,12:04:38.004,9.8257,9.1855,8.1727,7.9598,5.3095,2.0016,5.3646,...,119.670776,53.0,8224.983668,4607.356201,-1114.157508,662.330623,-762.931999,563.748359,1830.000019,0
3,3,1,12:04:38.006,12.2397,11.2825,10.5597,9.5310,7.6492,3.5774,7.4899,...,121.524075,53.0,8379.215326,4552.647571,-1094.587242,672.874212,-801.660294,595.436762,1830.000000,0
4,4,1,12:04:38.008,14.2806,13.2718,12.5526,11.1866,9.7840,5.2566,9.5088,...,123.518249,53.0,8522.097990,4501.825960,-1028.611317,686.878534,-835.992392,623.750109,1829.999987,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376499,15496,1,12:21:18.992,9.2943,9.6876,10.3244,7.0240,3.0805,4.1297,6.2661,...,31.640355,53.0,2297.563825,-4691.893544,5152.106229,239.860585,-93.515213,-120.277185,1717.036018,0
376500,15497,1,12:21:18.994,7.1350,7.8491,8.3672,5.0482,1.0098,2.0406,3.9025,...,32.124291,53.0,2315.321543,-4610.352638,5212.196311,265.331276,-108.524961,-116.801796,1717.078029,0
376501,15498,1,12:21:18.996,4.7637,5.5722,6.1365,2.8504,-1.1679,-0.2234,1.2927,...,32.588048,53.0,2329.397348,-4522.164960,5268.833279,291.371674,-124.077102,-112.887814,1717.102032,0
376502,15499,1,12:21:18.998,2.5854,3.4340,4.1226,0.9291,-2.8220,-2.0143,-0.5864,...,33.167871,53.0,2334.915435,-4442.118188,5310.580164,315.941382,-139.219496,-107.849222,1717.084023,0
376503,15500,1,12:21:19,0.4156,1.2608,2.1697,-0.9712,-4.2119,-3.6648,-1.9651,...,34.000000,53.0,2327.000000,-4385.000000,5326.000000,337.000000,-153.000000,-101.000000,1717.000000,0

In [16]:
new_col = [1] * a.shape[0]
a.insert(0, 'person', new_col)
a

,person,2,3,4,5,6,7,8,9,10,...,51,52,53,54,55,56,57,58,59,60
0,1,7.0640,7.3853,5.3534,6.9240,3.7559,1.7674,4.4223,6.7464,10.7780,...,115.000000,53.0,7865.000000,4712.000000,-1087.000000,661.000000,-688.000000,509.000000,1830.000000,0
1,1,7.8537,7.6998,6.1821,6.9615,3.8015,1.2309,4.1826,6.7128,10.5566,...,117.611651,53.0,8055.034673,4661.843221,-1105.551850,657.591356,-723.735803,533.373304,1830.000025,0
2,1,9.8257,9.1855,8.1727,7.9598,5.3095,2.0016,5.3646,7.9092,12.0235,...,119.670776,53.0,8224.983668,4607.356201,-1114.157508,662.330623,-762.931999,563.748359,1830.000019,0
3,1,12.2397,11.2825,10.5597,9.5310,7.6492,3.5774,7.4899,9.7218,14.5659,...,121.524075,53.0,8379.215326,4552.647571,-1094.587242,672.874212,-801.660294,595.436762,1830.000000,0
4,1,14.2806,13.2718,12.5526,11.1866,9.7840,5.2566,9.5088,11.3648,16.6226,...,123.518249,53.0,8522.097990,4501.825960,-1028.611317,686.878534,-835.992392,623.750109,1829.999987,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180496,1,13.4574,12.9637,10.9016,10.6666,10.1241,7.7911,7.6474,7.9377,4.9420,...,19.056476,53.0,2334.056457,7361.136505,3317.507941,98.715799,76.215742,-7.082927,1640.000109,0
180497,1,15.0615,15.5597,12.3495,12.8891,11.3221,10.5797,9.5361,9.2444,7.5713,...,18.681402,53.0,2328.933310,7358.299737,3316.900268,99.606686,77.931527,-7.179571,1640.000135,0
180498,1,16.3636,17.3752,13.4653,15.0994,12.4483,13.6728,11.3722,10.5227,10.8216,...,18.078089,53.0,2324.381935,7351.694716,3316.438623,100.539672,79.239440,-7.234752,1640.000107,0
180499,1,16.6670,17.7780,13.6059,16.6160,13.0492,16.4723,12.6855,11.2524,14.1313,...,17.449851,53.0,2321.153707,7343.526463,3316.384653,101.381772,80.231569,-7.193288,1640.000053,0
180500,1,15.9352,16.9962,12.8189,16.9944,13.0086,18.3942,13.2824,11.2792,16.7962,...,17.000000,53.0,2320.000000,7336.000000,3317.000000,102.000000,81.000000,-7.000000,1640.000000,0

In [19]:
a

,person,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c50,c51,c52,c53,c54,c55,c56,c57,c58,O
0,1,7.0640,7.3853,5.3534,6.9240,3.7559,1.7674,4.4223,6.7464,10.7780,...,115.000000,53.0,7865.000000,4712.000000,-1087.000000,661.000000,-688.000000,509.000000,1830.000000,0
1,1,7.8537,7.6998,6.1821,6.9615,3.8015,1.2309,4.1826,6.7128,10.5566,...,117.611651,53.0,8055.034673,4661.843221,-1105.551850,657.591356,-723.735803,533.373304,1830.000025,0
2,1,9.8257,9.1855,8.1727,7.9598,5.3095,2.0016,5.3646,7.9092,12.0235,...,119.670776,53.0,8224.983668,4607.356201,-1114.157508,662.330623,-762.931999,563.748359,1830.000019,0
3,1,12.2397,11.2825,10.5597,9.5310,7.6492,3.5774,7.4899,9.7218,14.5659,...,121.524075,53.0,8379.215326,4552.647571,-1094.587242,672.874212,-801.660294,595.436762,1830.000000,0
4,1,14.2806,13.2718,12.5526,11.1866,9.7840,5.2566,9.5088,11.3648,16.6226,...,123.518249,53.0,8522.097990,4501.825960,-1028.611317,686.878534,-835.992392,623.750109,1829.999987,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180496,1,13.4574,12.9637,10.9016,10.6666,10.1241,7.7911,7.6474,7.9377,4.9420,...,19.056476,53.0,2334.056457,7361.136505,3317.507941,98.715799,76.215742,-7.082927,1640.000109,0
180497,1,15.0615,15.5597,12.3495,12.8891,11.3221,10.5797,9.5361,9.2444,7.5713,...,18.681402,53.0,2328.933310,7358.299737,3316.900268,99.606686,77.931527,-7.179571,1640.000135,0
180498,1,16.3636,17.3752,13.4653,15.0994,12.4483,13.6728,11.3722,10.5227,10.8216,...,18.078089,53.0,2324.381935,7351.694716,3316.438623,100.539672,79.239440,-7.234752,1640.000107,0
180499,1,16.6670,17.7780,13.6059,16.6160,13.0492,16.4723,12.6855,11.2524,14.1313,...,17.449851,53.0,2321.153707,7343.526463,3316.384653,101.381772,80.231569,-7.193288,1640.000053,0
180500,1,15.9352,16.9962,12.8189,16.9944,13.0086,18.3942,13.2824,11.2792,16.7962,...,17.000000,53.0,2320.000000,7336.000000,3317.000000,102.000000,81.000000,-7.000000,1640.000000,0

In [17]:
a.columns=  columns

In [18]:
a

,person,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c50,c51,c52,c53,c54,c55,c56,c57,c58,O
0,1,7.0640,7.3853,5.3534,6.9240,3.7559,1.7674,4.4223,6.7464,10.7780,...,115.000000,53.0,7865.000000,4712.000000,-1087.000000,661.000000,-688.000000,509.000000,1830.000000,0
1,1,7.8537,7.6998,6.1821,6.9615,3.8015,1.2309,4.1826,6.7128,10.5566,...,117.611651,53.0,8055.034673,4661.843221,-1105.551850,657.591356,-723.735803,533.373304,1830.000025,0
2,1,9.8257,9.1855,8.1727,7.9598,5.3095,2.0016,5.3646,7.9092,12.0235,...,119.670776,53.0,8224.983668,4607.356201,-1114.157508,662.330623,-762.931999,563.748359,1830.000019,0
3,1,12.2397,11.2825,10.5597,9.5310,7.6492,3.5774,7.4899,9.7218,14.5659,...,121.524075,53.0,8379.215326,4552.647571,-1094.587242,672.874212,-801.660294,595.436762,1830.000000,0
4,1,14.2806,13.2718,12.5526,11.1866,9.7840,5.2566,9.5088,11.3648,16.6226,...,123.518249,53.0,8522.097990,4501.825960,-1028.611317,686.878534,-835.992392,623.750109,1829.999987,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180496,1,13.4574,12.9637,10.9016,10.6666,10.1241,7.7911,7.6474,7.9377,4.9420,...,19.056476,53.0,2334.056457,7361.136505,3317.507941,98.715799,76.215742,-7.082927,1640.000109,0
180497,1,15.0615,15.5597,12.3495,12.8891,11.3221,10.5797,9.5361,9.2444,7.5713,...,18.681402,53.0,2328.933310,7358.299737,3316.900268,99.606686,77.931527,-7.179571,1640.000135,0
180498,1,16.3636,17.3752,13.4653,15.0994,12.4483,13.6728,11.3722,10.5227,10.8216,...,18.078089,53.0,2324.381935,7351.694716,3316.438623,100.539672,79.239440,-7.234752,1640.000107,0
180499,1,16.6670,17.7780,13.6059,16.6160,13.0492,16.4723,12.6855,11.2524,14.1313,...,17.449851,53.0,2321.153707,7343.526463,3316.384653,101.381772,80.231569,-7.193288,1640.000053,0
180500,1,15.9352,16.9962,12.8189,16.9944,13.0086,18.3942,13.2824,11.2792,16.7962,...,17.000000,53.0,2320.000000,7336.000000,3317.000000,102.000000,81.000000,-7.000000,1640.000000,0